import pytest
from models.group import Group
from schemas.group import GroupCreate, GroupUpdate
from services.group_service import GroupService
from sqlalchemy.exc import NoResultFound


class MockGroupRepository:
    """
    Provides an in-memory mock implementation of a group repository for testing.
    """

    def __init__(self):
        self.groups = {}
        self.counter = 1

    def add(self, group: Group):
        group.id = self.counter
        # Ensure invitation_code is stored if generated by service
        if not hasattr(group, "invitation_code"):
            group.invitation_code = "TESTCODE" 
        
        self.groups[self.counter] = group
        self.counter += 1
        return group

    def get_by_id(self, group_id: int):
        return self.groups.get(group_id)

    def get_by_name(self, name: str):
        for g in self.groups.values():
            if g.name == name:
                return g
        return None
    
    def get_by_invitation_code(self, code: str):
        """
        Retrieves a group by invitation code.
        """
        for g in self.groups.values():
            if hasattr(g, "invitation_code") and g.invitation_code == code:
                return g
        return None

    def get_all(self, offset: int = 0, limit: int = 100):
        groups = list(self.groups.values())
        return groups[offset: offset + limit]

    def update(self, group_id: int, fields: dict):
        group = self.groups.get(group_id)
        for key, value in fields.items():
            setattr(group, key, value)
        return group

    def delete(self, group_id: int):
        if group_id not in self.groups:
            pass # emulate void return or raise depending on real repo behavior, usually delete is idempotent or raises
        if group_id in self.groups:
            del self.groups[group_id]


@pytest.fixture
def mock_repo():
    return MockGroupRepository()


@pytest.fixture
def group_service(mock_repo):
    return GroupService(mock_repo)


@pytest.fixture
def sample_group_data():
    return {"name": "Trip Crew", "description": "Friends going on a trip"}


def test_create_group(group_service, mock_repo, sample_group_data):
    data = GroupCreate(**sample_group_data)
    group = group_service.create_group(data)

    assert group.id == 1
    assert group.name == "Trip Crew"
    assert len(mock_repo.groups) == 1


def test_get_group_by_id_success(group_service, mock_repo, sample_group_data):
    created = group_service.create_group(GroupCreate(**sample_group_data))
    retrieved = group_service.get_group_by_id(created.id)

    assert retrieved.id == created.id
    assert retrieved.name == created.name


def test_get_group_by_id_not_found(group_service):
    with pytest.raises(NoResultFound):
        group_service.get_group_by_id(999)


def test_get_group_by_name_success(group_service, mock_repo, sample_group_data):
    created = group_service.create_group(GroupCreate(**sample_group_data))
    retrieved = group_service.get_group_by_name("Trip Crew")

    assert retrieved.id == created.id
    assert retrieved.name == "Trip Crew"


def test_get_group_by_name_not_found(group_service):
    with pytest.raises(NoResultFound):
        group_service.get_group_by_name("Missing Group")


def test_get_all_groups(group_service, mock_repo):
    group_service.create_group(GroupCreate(name="G1"))
    group_service.create_group(GroupCreate(name="G2"))

    result = group_service.get_all_groups()

    assert len(result) == 2
    assert result[0].name == "G1"
    assert result[1].name == "G2"


def test_update_group_success(group_service, mock_repo, sample_group_data):
    created = group_service.create_group(GroupCreate(**sample_group_data))

    update_data = GroupUpdate(description="New description")
    updated = group_service.update_group(created.id, update_data)

    assert updated.description == "New description"
    assert mock_repo.groups[created.id].description == "New description"


def test_update_group_not_found(group_service):
    with pytest.raises(NoResultFound):
        group_service.update_group(999, GroupUpdate(description="x"))


def test_update_group_no_fields(group_service, mock_repo, sample_group_data):
    created = group_service.create_group(GroupCreate(**sample_group_data))

    with pytest.raises(ValueError):
        group_service.update_group(created.id, GroupUpdate())


def test_delete_group_success(group_service, mock_repo, sample_group_data):
    created = group_service.create_group(GroupCreate(**sample_group_data))
    assert len(mock_repo.groups) == 1

    group_service.delete_group(created.id)

    assert len(mock_repo.groups) == 0


def test_delete_group_not_found(group_service):
    with pytest.raises(NoResultFound):
        group_service.delete_group(123)