package com.example.budgeting.android.data.model

import com.squareup.moshi.Json

/**
 * Expense model matching the backend schema.
 * Backend schema: id (int, required), user_id (int?, optional), group_id (int?, optional),
 * title (str, required), category (str, required), amount (float, required), created_at (datetime, required)
 * 
 * Note: id and created_at are nullable to support creating new expenses (they're generated by backend),
 * but when receiving from backend, they should always be present. However, we make them nullable
 * to handle cases where the backend might return malformed data.
 */
data class Expense(
    @Json(name = "id")
    val id: Int? = null,
    
    @Json(name = "user_id")
    var user_id: Int? = null,
    
    @Json(name = "group_id")
    val group_id: Int? = null,
    
    @Json(name = "title")
    val title: String,
    
    @Json(name = "category")
    val category: String,
    
    @Json(name = "amount")
    val amount: Double,
    
    @Json(name = "created_at")
    val created_at: String? = null
)
